name: Build and backup docker container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: docker/setup-buildx-action@v4
    - name: Build the Docker image
      run: docker buildx build -t everdo-docker . --tag my-image-name:latest
